backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

collections:
  - name: pages
    label: Pages
    folder: __tests__/md/pages
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Path, name: path, widget: string}
      - {label: Content, name: content, widget: markdown}
  - name: layout
    label: Layout
    files:
      - label: Navbar
        name: navbar
        file: __tests__/md/layout/navbar.md
        fields:
          - {label: Title, name: title, widget: string}
      - label: Footer
        name: footer
        file: __tests__/md/layout/footer.md
        fields:
          - {label: Content, name: content, widget: markdown}
          - {label: Copyright, name: copyright, widget: text}